### ISSUE TITLE
local.ERROR: exception 'Yajra\Pdo\Oci8\Exceptions\Oci8Exception' with message 'Error Code    : 909

### ISSUE THREAD

**Issue by pringgojs** [yajra/laravel-oci8#469]
Error occurs when i am using CONCAT function in my eloquent

Environment

> PHP 5.4.45
Laravel 5.0.33
yajra/laravel-oci8 ~2.0
Oracle 11g Enterprise Release 11.2.0.1.0 

Source Code in Controller
```php
return Kuliah::semester()->get();

```
Source Code in the `Kuliah Model`
```php
public function scopeSemester($q)
{
     $q->select(\DB::raw("CONCAT(tahun,'/',semester ) AS semester"), 'tahun')->groupBy('tahun')->groupBy('semester')->orderBy('semester', 'DESC');
}
```

Error log
```
[2018-10-24 14:13:06] local.ERROR: exception 'Yajra\Pdo\Oci8\Exceptions\Oci8Exception' with message 'Error Code    : 909
Error Message : ORA-00909: invalid number of arguments
Position      : 7
Statement     : select CONCAT(tahun,'/',semester ) AS semester, tahun from kuliah group by tahun, semester order by semester desc
Bindings      : []
' in D:\SIM\api\vendor\yajra\laravel-pdo-via-oci8\src\Pdo\Oci8\Statement.php:182
Stack trace:
#0 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(294): Yajra\Pdo\Oci8\Statement->execute(Array)
#1 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(616): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(yajra\Oci8\Oci8Connection), 'select CONCAT(t...', Array)
#2 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(580): Illuminate\Database\Connection->runQueryCallback('select CONCAT(t...', Array, Object(Closure))
#3 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Connection.php(297): Illuminate\Database\Connection->run('select CONCAT(t...', Array, Object(Closure))
#4 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1377): Illuminate\Database\Connection->select('select CONCAT(t...', Array, true)
#5 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1367): Illuminate\Database\Query\Builder->runSelect()
#6 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1354): Illuminate\Database\Query\Builder->getFresh(Array)
#7 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(380): Illuminate\Database\Query\Builder->get(Array)
#8 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(162): Illuminate\Database\Eloquent\Builder->getModels(Array)
#9 D:\SIM\api\app\Http\Controllers\Lecturer\FilterController.php(15): Illuminate\Database\Eloquent\Builder->get()
#10 [internal function]: App\Http\Controllers\Lecturer\FilterController->getSemester()
#11 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(246): call_user_func_array(Array, Array)
#12 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('getSemester', Array)
#13 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Lecturer\FilterController), Object(Illuminate\Routing\Route), 'getSemester')
#14 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Lecturer\FilterController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getSemester')
#20 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'getSemester')
#21 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#22 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#32 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 D:\SIM\api\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 D:\SIM\api\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 D:\SIM\api\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}

```

**Comment by yajra** [comment]
I think your SQL is wrong and maybe you should group by concat too?

```php
->groupBy(DB::raw("CONCAT(tahun,'/',semester )"))
```

**Comment by pringgojs** [comment]
I have changed my code to like, but still get the same error

```php
public function scopeSemester($q)
{
     $q->select(\DB::raw("CONCAT(tahun,'/',semester ) AS semester"), 'tahun')->groupBy(\DB::raw("CONCAT(tahun,'/',semester )"))->orderBy('semester', 'DESC');
}

**Comment by yajra** [comment]
AFAIK, your'e selecting 2 columns which is not aggregate thus you also need to group by 2 columns.

```php
public function scopeSemester($q)
{
     $q->select(\DB::raw("CONCAT(tahun,'/',semester ) AS semester"), 'tahun')
->groupBy(\DB::raw("CONCAT(tahun,'/',semester )"))
->groupBy('tahun')
->orderBy('semester', 'DESC');
}
```

**Comment by pringgojs** [comment]
thank you for trying to help me, but I still get the same error code when I changed the code like this.

```php
public function scopeSemester($q)
{
        $q->select(\DB::raw("CONCAT(tahun,'/',semester ) AS semester"), 'tahun')
	    ->groupBy(\DB::raw("CONCAT(tahun,'/',semester )"))
            ->groupBy('tahun')
	    ->orderBy('semester', 'DESC');
}
```

**Comment by pringgojs** [comment]
At Oracle Developer, I tried writing a query like this ,and working well. 

```sql
select (tahun || '/' || semester ) AS semester, tahun from kuliah 
group by semester, tahun order by tahun desc
```

But when i am typing like this not working
```sql
select CONCAT(tahun,'/',semester ) AS semester, tahun from kuliah group by CONCAT(tahun,'/',semester ), tahun order by tahun desc
```

**Comment by yajra** [comment]
I see now, I think concat only accepts 2 param.

```php
public function scopeSemester($q)
{
        $q->select(\DB::raw("(tahun || '/' || semester ) AS semester"), 'tahun')
	    ->groupBy(\DB::raw("(tahun || '/' || semester )"))
            ->groupBy('tahun')
	    ->orderBy('semester', 'DESC');
}
```

**Comment by pringgojs** [comment]
Thank you @yajra , it's working well. 

but went i am trying with MySQL database, this eloquent not working. Will you fix this so that when I move the database from Oracle to mysql my application is not an error? Thanks before

**Comment by yajra** [comment]
Unfortunately, `concat` seems to differs on which DB you are using. Maybe you should try using accessors/mutators to safely concat the data. I think we cannot fix this on the package level.
