### ISSUE TITLE
Scheduled task not working

### ISSUE THREAD

**Issue by RiccardoFrancescato** [yajra/laravel-oci8#515]
### Summary of problem or feature request
I'm setting up a scheduled job thet fetch data from oracle db and transfer them locally.
the cron job is

```
* * * * * cd /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/ && php artisan schedule:run > /dev/null 2>&1
```

if i run php artisan schedule:run from a terminal window all works fine and data are correctly imported, when cron runs the job in logs i see errors and job fail.

```
[2019-07-24 09:41:00] local.ERROR: Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' {"exception":"[object] (ErrorException(code: 0): Use of undefined constant OCI_CRED_EXT - assumed 'OCI_CRED_EXT' at /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/yajra/laravel-oci8/src/Oci8/Connectors/OracleConnector.php:36)
[stacktrace]
#0 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/yajra/laravel-oci8/src/Oci8/Connectors/OracleConnector.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Use of undefine...', '/Users/Riccardo...', 36, Array)
#1 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/yajra/laravel-oci8/src/Oci8/Oci8ServiceProvider.php(49): Yajra\\Oci8\\Connectors\\OracleConnector->connect(Array)
#2 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(269): Yajra\\Oci8\\Oci8ServiceProvider->Yajra\\Oci8\\{closure}(Object(Closure), '', '', Array)
#3 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(76): Illuminate\\Database\\Connectors\\ConnectionFactory->createConnection('oracle', Object(Closure), '', '', Array)
#4 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(50): Illuminate\\Database\\Connectors\\ConnectionFactory->createSingleConnection(Array)
#5 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(131): Illuminate\\Database\\Connectors\\ConnectionFactory->make(Array, 'click')
#6 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(86): Illuminate\\Database\\DatabaseManager->makeConnection('click')
#7 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Database\\DatabaseManager->connection('click')
#8 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/app/Console/FetchProductiondata.php(21): Illuminate\\Support\\Facades\\Facade::__callStatic('connection', Array)
#9 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/app/Console/Kernel.php(32): App\\Console\\FetchProductiondata::fetch()
#10 [internal function]: App\\Console\\Kernel->App\\Console\\{closure}()
#11 [internal function]: Closure->__invoke()
#12 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#13 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Console/Scheduling/CallbackEvent.php(75): Illuminate\\Container\\Container->call(Array, Array)
#17 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(111): Illuminate\\Console\\Scheduling\\CallbackEvent->run(Object(Illuminate\\Foundation\\Application))
#18 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(75): Illuminate\\Console\\Scheduling\\ScheduleRunCommand->runEvent(Object(Illuminate\\Console\\Scheduling\\CallbackEvent))
#19 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle()
#20 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#21 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#25 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#26 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /Users/Riccardo.Francescato/Repos/Lean/TaktBackend/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 {main}
"} 

```

### Code snippet of problem

```php
 $schedule->call(function () {
            FetchProductiondata::fetch();
        })->everyMinute();
```

### System details

- Operating System Mac 10.14.5
- PHP Version 7.3
- Laravel Version 5.8
- Laravel-OCI8 Version 5.8.2

**Comment by williams-young** [comment]
I have the same question. I tried #506 `s solutions ,but it doesn`t work.
Operating System Mac 10.15.3
PHP Version 7.2
Laravel Version 6.2
Laravel-OCI8 Version 6.2
Apache2

**Comment by SANfen** [comment]
Who has a solution。Consult me

**Comment by SANfen** [comment]
My problem is solved. The reason is that the site USES PHP-FPM 7.2 while the extension I asked is installed in 7.1. I just switched the VERSION of PHP-FPM

**Comment by einnar82** [comment]
You may check my comment in this thread #506
