### ISSUE TITLE
ORA-02396: exceeded maximum idle time, please connect again

### ISSUE THREAD

**Issue by adipradewa25** [yajra/laravel-oci8#892]
### Summary of problem or feature request

```
Error Code    : 2396
Error Message : ORA-02396: exceeded maximum idle time, please connect again
```

### Code snippet of problem

```
Error Code    : 2396
Error Message : ORA-02396: exceeded maximum idle time, please connect again
Position      : 0
Statement     : ALTER SESSION SET NLS_TIME_FORMAT  = 'HH24:MI:SS' NLS_DATE_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT  = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS  = '.,'
Bindings      : []
 (Connection: oracle, SQL: ALTER SESSION SET NLS_TIME_FORMAT  = 'HH24:MI:SS' NLS_DATE_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT  = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS  = '.,') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2396): Error Code    : 2396
Error Message : ORA-02396: exceeded maximum idle time, please connect again
Position      : 0
Statement     : ALTER SESSION SET NLS_TIME_FORMAT  = 'HH24:MI:SS' NLS_DATE_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT  = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS  = '.,'
Bindings      : []
 (Connection: oracle, SQL: ALTER SESSION SET NLS_TIME_FORMAT  = 'HH24:MI:SS' NLS_DATE_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT  = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT  = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS  = '.,') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\\Database\\Connection->runQueryCallback('ALTER SESSION S...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(560): Illuminate\\Database\\Connection->run('ALTER SESSION S...', Array, Object(Closure))
#2 /var/www/html/vendor/yajra/laravel-oci8/src/Oci8/Oci8Connection.php(99): Illuminate\\Database\\Connection->statement('ALTER SESSION S...')
#3 /var/www/html/vendor/yajra/laravel-oci8/src/Oci8/Oci8ServiceProvider.php(91): Yajra\\Oci8\\Oci8Connection->setSessionVars(Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(270): Yajra\\Oci8\\Oci8ServiceProvider->Yajra\\Oci8\\{closure}(Object(Yajra\\Pdo\\Oci8), '', '', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(76): Illuminate\\Database\\Connectors\\ConnectionFactory->createConnection('oracle', Object(Closure), '', '', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(51): Illuminate\\Database\\Connectors\\ConnectionFactory->createSingleConnection(Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(167): Illuminate\\Database\\Connectors\\ConnectionFactory->make(Array, 'oracle')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(334): Illuminate\\Database\\DatabaseManager->makeConnection('oracle')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(302): Illuminate\\Database\\DatabaseManager->refreshPdoConnections('oracle')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(72): Illuminate\\Database\\DatabaseManager->reconnect('oracle')
#11 [internal function]: Illuminate\\Database\\DatabaseManager->Illuminate\\Database\\{closure}(Object(Yajra\\Oci8\\Oci8Connection))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(995): call_user_func(Object(Closure), Object(Yajra\\Oci8\\Oci8Connection))
#13 /var/www/html/app/Models/TaraModel.php(194): Illuminate\\Database\\Connection->reconnect()
#14 /var/www/html/app/Jobs/GetStatusEfakturJob.php(37): App\\Models\\TaraModel->getStatusFaktur()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\GetStatusEfakturJob->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\GetStatusEfakturJob))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\GetStatusEfakturJob))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\GetStatusEfakturJob), false)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\GetStatusEfakturJob))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\GetStatusEfakturJob))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(71): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(App\\Jobs\\GetStatusEfakturJob))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(439): Illuminate\\Queue\\Jobs\\Job->fire()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(389): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(176): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(139): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(122): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call(Array)
#41 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#43 /var/www/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 {main}
```

### System details

- Operating System 
- PHP Version : dunglas/frankenphp:1.2.4-php8.2.22
- Laravel Version : 11.21
- Laravel-OCI8 Version : 11.6

Hii,
can help me i facing error like that,
i have already use $db->reconnect() before query script and use $db->disconnect() in end of code ;
```
if(env('APP_ENV') == 'production'){
    $db = DB::connection('oracle');
}else{
    $db = DB::connection('oracleDev');
}
$db->reconnect();
$dbTable = $db->table('BILLING.T_TRANSACTION_TAX');
$dbTable->whereNull('STATUS');
$dbTable->whereNotNull('NO_FAKTUR');
$result = $dbTable->get();
$db->disconnect();
return $result;
```
but the error is always facing

**Comment by yajra** [comment]
I haven't encountered this issue yet. 

Suggestion, try using a persistent connection. See https://github.com/yajra/laravel-oci8/issues/169

```php
'oracle' => [
        'driver'   => 'oracle',
        'tns'      => env('DB_TNS', ''),
        'host'     => env('DB_HOST', ''),
        'port'     => env('DB_PORT', '1521'),
        'database' => env('DB_DATABASE', ''),
        'username' => env('DB_USERNAME', ''),
        'password' => env('DB_PASSWORD', ''),
        'charset'  => env('DB_CHARSET', 'AL32UTF8'),
        'prefix'   => env('DB_PREFIX', ''),
        'options'   => [
            PDO::ATTR_PERSISTENT => true,
        ],
],
```
